src/SME_UnB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^transductor/', include('transductor.urls',
                                  namespace="transductor")),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^reports/', include('report.urls', namespace="report")),
    url(r'^retrieve_password/', include('retrieve_password.urls', namespace="retrieve")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/report/urls.py
from django.conf.urls import url

from . import views

app_name = 'report'
urlpatterns = [
    url(r'^report/(?P<transductor_id>[0-9]+)/$', views.report, name="report"),
    url(r'^open_pdf/(?P<transductor_id>[0-9]+)/$', views.open_pdf, name="open_pdf"),
    url(r'^invoice/(?P<transductor_id>[0-9]+)/$', views.invoice, name="invoice"),
    url(r'^transductors_filter/$', views.transductors_filter, name="transductors_filter"),
    url(r'^transductor_list/$', views.transductor_list, name="transductor_list"),
    url(r'^get_data_by_transductor/(?P<transductor_id>[0-9]+)/$', views.get_measurements_filter_transductor, name="get_measurements_filter_transductor"),
    url(r'^list_transductors/$', views.list_transductors, name="list_transductors"),
    url(r'^return_chart/$', views.return_chart, name="return_chart"),
]

src/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^$', views.show_login, name="home"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="list_user_edit"),
    url(r'^list_user_delete/',
        views.list_user_delete,
        name="list_user_delete"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/',
        views.edit_user,
        name="edit_user"),
    url(r'^delete_user/(?P<user_id>[0-9]+)/',
        views.delete_user,
        name="delete_user"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^logging_list/', views.logging_list, name="logging_list"),
    url(r'^change_password/', views.change_password, name="change_password"),
]

src/report/models.py
from __future__ import unicode_literals

from django.db import models


class Report(models.Model):

    class Meta:
        permissions = (
            ("can_generate", "Can Generate Reports"),
        )
    """Function to fix single permission exception"""

    def _get_all_permissions(opts, ctype):
        builtin = _get_builtin_permissions(opts)
        custom = list(opts.permissions)
        _check_permission_clashing(custom, builtin, ctype)
        return builtin + custom

src/report/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse_lazy, reverse
from django.core import serializers
from cStringIO import StringIO
from reportlab.platypus.flowables import Image
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

from django.http import HttpResponse
from django.utils.translation import ugettext as _

import datetime

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter
import matplotlib.patches as mpatches

from transductor.models import EnergyMeasurements, EnergyTransductor
from transductor.models import TransductorModel
import json


def create_graphic(path, array_date, array_dateb,
                   array_datec, array_data, label):
    title = _('Monitoring') + ' ' + label

    fig = Figure()

    ax = fig.add_subplot(111)
    bx = fig.add_subplot(111)
    cx = fig.add_subplot(111)
    x = []
    y = []
    yb = []
    yc = []
    xb = []
    xc = []

    for i in range(len(array_data)):
        x.append(array_data[i])
        y.append(array_date[i])
        xb.append(array_data[i])
        xc.append(array_data[i])
        yb.append(array_dateb[i])
        yc.append(array_datec[i])

    ax.plot_date(x, y, '-')
    bx.plot_date(xb, yb, '-')
    cx.plot_date(xc, yc, '-')

    patch1 = mpatches.Patch(color='blue', label=_('Phase 1'))
    patch2 = mpatches.Patch(color='green', label=_('Phase 2'))
    patch3 = mpatches.Patch(color='red', label=_('Phase 3'))

    z = [patch1, patch2, patch3]

    cx.legend(handles=z, loc=1)

    ax.set_title(title)
    ax.set_xlabel(_('Date'))
    ax.set_ylabel(label)
    ax.xaxis.set_major_formatter(DateFormatter('%Y-%m-%d'))
    fig.autofmt_xdate()
    canvas = FigureCanvas(fig)

    fig.savefig(path)

    return path


def generatePdf(transductor_id):
    import time
    from reportlab.lib.enums import TA_JUSTIFY
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch

    doc = SimpleDocTemplate("src/report/static/Relatorio"+transductor_id+".pdf",
                            pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    Story = []
    logo = "src/report/static/currentGraphic"+transductor_id+".png"
    logo2 = "src/report/static/voltageGraphic"+transductor_id+".png"
    logo3 = "src/report/static/activePowerGraphic"+transductor_id+".png"
    logo4 = "src/report/static/reactivePowerGraphic"+transductor_id+".png"
    logo5 = "src/report/static/apparentPowerGraphic"+transductor_id+".png"

    magName = "Pythonista"
    issueNum = 12
    subPrice = "99.00"
    limitedDate = "03/05/2010"
    freeGift = "tin foil hat"

    formatted_time = time.ctime()
    full_name = "SME-UnB"
    address_parts = ["Campus Universitario UnB", "Brasilia-DF, 70910-900"]

    im = Image(logo, 8 * inch, 5 * inch)
    im2 = Image(logo2, 8 * inch, 5 * inch)
    im3 = Image(logo3, 8 * inch, 5 * inch)
    im4 = Image(logo4, 8 * inch, 5 * inch)
    im5 = Image(logo5, 8 * inch, 5 * inch)

    Story.append(im)
    Story.append(im2)
    Story.append(im3)
    Story.append(im4)
    Story.append(im5)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
    ptext = '<font size=12>%s</font>' % formatted_time

    Story.append(Paragraph(ptext, styles["Normal"]))
    Story.append(Spacer(1, 12))

    ptext = '<font size=12>%s</font>' % full_name
    Story.append(Paragraph(ptext, styles["Normal"]))
    for part in address_parts:
        ptext = '<font size=12>%s</font>' % part.strip()
        Story.append(Paragraph(ptext, styles["Normal"]))

    Story.append(Spacer(1, 12))
    Story.append(Spacer(1, 12))
    ptext = '<font size=12>{ % trans Report Energy Monitoring % }</font>'
    Story.append(Paragraph(ptext, styles["Normal"]))

    doc.build(Story)
    return 1


def __minValue(arrayData):

    arrayData.sort()
    return arrayData[0]


def __maxValue(arrayData):

    arrayData.sort(reverse=True)

    return arrayData[0]


def __average(arrayData):
    total = 0
    for i in arrayData:
        total += i

    if(len(arrayData) != 0):
        return total / len(arrayData)
    else:
        return 0

@login_required
def report(request, transductor_id):
    now = datetime.datetime.now()
    delta = datetime.timedelta(days=1)

    date = []
    data = []

    voltage_a = []
    voltage_b = []
    voltage_c = []
    current_a = []
    current_b = []
    current_c = []
    active_power_a = []
    active_power_b = []
    active_power_c = []
    reactive_power_a = []
    reactive_power_b = []
    reactive_power_c = []
    apparent_power_a = []
    apparent_power_b = []
    apparent_power_c = []

    for i in EnergyMeasurements.objects.all().filter(transductor=EnergyTransductor.objects.get(id=transductor_id)):

        date.append(i.collection_date)
        voltage_a.append(i.voltage_a)
        voltage_b.append(i.voltage_b)
        voltage_c.append(i.voltage_c)
        current_a.append(i.current_a)
        current_b.append(i.current_b)
        current_c.append(i.current_c)
        active_power_a.append(i.active_power_a)
        active_power_b.append(i.active_power_b)
        active_power_c.append(i.active_power_c)
        reactive_power_a.append(i.reactive_power_a)
        reactive_power_b.append(i.reactive_power_b)
        reactive_power_c.append(i.reactive_power_c)
        apparent_power_a.append(i.apparent_power_a)
        apparent_power_b.append(i.apparent_power_b)
        apparent_power_c.append(i.apparent_power_c)


    create_graphic(
        'src/report/static/currentGraphic' + transductor_id + '.png',
        current_a,
        current_b,
        current_c,
        date,
        _('Current'))

    create_graphic(
        'src/report/static/voltageGraphic' + transductor_id + '.png',
        voltage_a,
        voltage_b,
        voltage_c,
        date,
        _('Voltage'))

    create_graphic(
        'src/report/static/activePowerGraphic' + transductor_id + '.png',
        active_power_a,
        active_power_b,
        active_power_c,
        date,
        _('Active Power'))

    create_graphic(
        'src/report/static/reactivePowerGraphic' + transductor_id + '.png',
        reactive_power_a,
        reactive_power_b,
        reactive_power_c,
        date,
        _('Reactive Power'))

    create_graphic(
        'src/report/static/apparentPowerGraphic' + transductor_id + '.png',
        apparent_power_a,
        apparent_power_b,
        apparent_power_c,
        date,
        _('Apparent Power'))

    generatePdf(transductor_id)

    maxVoltage = [__maxValue(voltage_a),
                  __maxValue(voltage_b),
                  __maxValue(voltage_c)]

    minVoltage = [__minValue(voltage_a),
                  __minValue(voltage_b),
                  __minValue(voltage_c)]

    averageVoltage = [__average(voltage_a),
                      __average(voltage_b),
                      __average(voltage_c)]

    maxCurrent = [__maxValue(current_a),
                  __maxValue(current_b),
                  __maxValue(current_c)]

    minCurrent = [__minValue(current_a),
                  __minValue(current_b),
                  __minValue(current_c)]

    averageCurrent = [__average(current_a),
                      __average(current_b),
                      __average(current_c)]

    maxActivePower = [__maxValue(active_power_a),
                      __maxValue(active_power_b),
                      __maxValue(active_power_c)]

    minActivePower = [__minValue(active_power_a),
                      __minValue(active_power_b),
                      __minValue(active_power_c)]

    averageActivePower = [__average(active_power_a),
                          __average(active_power_b),
                          __average(active_power_c)]

    maxReactivePower = [__maxValue(reactive_power_a),
                        __maxValue(reactive_power_b),
                        __maxValue(reactive_power_c)]

    minReactivePower = [__minValue(reactive_power_a),
                        __minValue(reactive_power_b),
                        __minValue(reactive_power_c)]

    averageReactivePower = [__average(reactive_power_a),
                            __average(reactive_power_b),
                            __average(reactive_power_c)]

    maxApparentPower = [__maxValue(apparent_power_a),
                        __maxValue(apparent_power_b),
                        __maxValue(apparent_power_c)]

    minApparentPower = [__minValue(apparent_power_a),
                        __minValue(apparent_power_b),
                        __minValue(apparent_power_c)]

    averageApparentPower = [__average(apparent_power_a),
                            __average(apparent_power_b),
                            __average(apparent_power_c)]

    VoltageInformation = {'max': maxVoltage, 'min': minVoltage,
                          'average': averageVoltage}

    currentInformation = {'max': maxCurrent, 'min': minCurrent,
                          'average': averageCurrent}

    activePowerInformation = {'max': maxActivePower, 'min': minActivePower,
                              'average': averageActivePower}

    reactivePowerInformation = {'max': maxReactivePower,
                                'min': minReactivePower,
                                'average': averageReactivePower}

    apparentPowerInformation = {'max': maxApparentPower,
                                'min': minApparentPower,
                                'average': averageApparentPower}

    information = {'voltage': VoltageInformation,
                   'Current': currentInformation,

src/report/templates/graphics/chart.html
{% extends "users/dashboard.html" %}
{% load i18n %}
{% load staticfiles %}
{% load static %}

{% block dashboard_content %}

<body>
  <div class="container-fluid">
    <div class="span2 well" id="select_transductor">
      <h3 class="info">{% trans "Choose A transductor"%}.</h3>
      <h5 class="info2">{% trans "Show graphics  of transductor"%}</h5>
      <select required class="form-control" id="selectTransductor" style="width: 40%;">
        <option value="" selected="true"> {% trans "Select a Transductor" %} </option>
        {% for transductor in all_transductors %}
        <option value="{{transductor.id}}">
          {{transductor.description}}
        </option>
        {% endfor %}
      </select>
      <button type="button" id="select_transductor_btn">{% trans "Select" %}</button>
    </div>

    <div class="container-fluid" id="dashboard_div">
      <div class="row">
        <div class="col-lg-2 well wll-sm" id="column_filter" hidden="true"></div>
        <div class="container col-lg-10" id="curve_chart"></div>
      </div>
      <div class="container row" id="filter_div"></div>
    </div>

  </div>
  <script src="{% static 'js/chart.js' %}"></script>
</body>
{% endblock %}

src/report/templates/graphics/report.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
<title>{% trans "Reports" %}</title>
{% endblock %}


{% block body %}


<div class="form-group">
  <h1 class='text-center'>{% trans "Report" %}</h1>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <a class="btn btn-primary btn-lg btn-block" href="{% url 'report:open_pdf' transductor_id %}" target="_blank" role="button">{% trans "Generate PDF" %}&raquo;</a>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3"></div>
  <div class="col-xs-6 col-md-6">
    <div class="form-group">
      {% load staticfiles %}
      <img src="{% static 'currentGraphic' %}{{transductor_id}}.png"/>
      <table class ="table table-bordered">
          <tr>
              <th>{% trans "Phase"%}</th>
              <th>{% trans "Max. value"%}</th>
              <th>{% trans "Min. Value"%}</th>
              <th>{% trans "Average Value"%}</th>
          </tr>
          <tr>
              <td>{% trans "Phase 1"%}</td>
              <td>{{Current.max.0}}</td>
              <td>{{Current.min.0}}</td>
              <td>{{Current.average.0}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 2"%}</td>
              <td>{{Current.max.1}}</td>
              <td>{{Current.min.1}}</td>
              <td>{{Current.average.1}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 3"%}</td>
              <td>{{Current.max.2}}</td>
              <td>{{Current.min.2}}</td>
              <td>{{Current.average.2}}</td>
          </tr>

      </table class ="table table-bordered">
    </div>
  </div>
</div>


<div class="row">
  <div class="col-xs-6 col-md-3"></div>
  <div class="col-xs-6 col-md-6">
    <div class="form-group">
      {% load staticfiles %}
      <img src="{% static  'voltageGraphic' %}{{transductor_id}}.png"/>
      <table class ="table table-bordered">
          <tr>
            <th>{% trans "Phase"%}</th>
            <th>{% trans "Max. value"%}</th>
            <th>{% trans "Min. Value"%}</th>
            <th>{% trans "Average Value"%}</th>
          </tr>
          <tr>
              <td>{% trans "Phase 1"%}</td>
              <td>{{voltage.max.0}}</td>
              <td>{{voltage.min.0}}</td>
              <td>{{voltage.average.0}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 2"%}</td>
              <td>{{voltage.max.1}}</td>
              <td>{{voltage.min.1}}</td>
              <td>{{voltage.average.1}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 3"%}</td>
              <td>{{voltage.max.2}}</td>
              <td>{{voltage.min.2}}</td>
              <td>{{voltage.average.2}}</td>
          </tr>

      </table class ="table table-bordered">

    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3"></div>
  <div class="col-xs-6 col-md-6">
    <div class="form-group">
      {% load staticfiles %}
      <img src="{% static  'activePowerGraphic' %}{{transductor_id}}.png"/>
      <table class ="table table-bordered">
          <tr>
            <th>{% trans "Phase"%}</th>
            <th>{% trans "Max. value"%}</th>
            <th>{% trans "Min. Value"%}</th>
            <th>{% trans "Average Value"%}</th>
          </tr>
          <tr>
              <td>{% trans "Phase 1"%}</td>
              <td>{{activePower.max.0}}</td>
              <td>{{activePower.min.0}}</td>
              <td>{{activePower.average.0}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 2"%}</td>
              <td>{{activePower.max.1}}</td>
              <td>{{activePower.min.1}}</td>
              <td>{{activePower.average.1}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 3"%}</td>
              <td>{{activePower.max.2}}</td>
              <td>{{activePower.min.2}}</td>
              <td>{{activePower.average.2}}</td>
          </tr>

      </table class ="table table-bordered">

    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3"></div>
  <div class="col-xs-6 col-md-6">
    <div class="form-group">
      {% load staticfiles %}
      <img src="{% static  'reactivePowerGraphic' %}{{transductor_id}}.png"/>
      <table class ="table table-bordered">
          <tr>
            <th>{% trans "Phase"%}</th>
            <th>{% trans "Max. value"%}</th>
            <th>{% trans "Min. Value"%}</th>
            <th>{% trans "Average Value"%}</th>
          </tr>
          <tr>
              <td>{% trans "Phase 1"%}</td>
              <td>{{reactivePower.max.0}}</td>
              <td>{{reactivePower.min.0}}</td>
              <td>{{reactivePower.average.0}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 2"%}</td>
              <td>{{reactivePower.max.1}}</td>
              <td>{{reactivePower.min.1}}</td>
              <td>{{reactivePower.average.1}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 3"%}</td>
              <td>{{reactivePower.max.2}}</td>
              <td>{{reactivePower.min.2}}</td>
              <td>{{reactivePower.average.2}}</td>
          </tr>

      </table class ="table table-bordered">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3"></div>
  <div class="col-xs-6 col-md-6">
    <div class="form-group">
      {% load staticfiles %}
      <img src="{% static 'apparentPowerGraphic' %}{{transductor_id}}.png"/>
      <table class ="table table-bordered">
          <tr>
            <th>{% trans "Phase"%}</th>
            <th>{% trans "Max. value"%}</th>
            <th>{% trans "Min. Value"%}</th>
            <th>{% trans "Average Value"%}</th>
          </tr>
          <tr>
              <td>{% trans "Phase 1"%}</td>
              <td>{{apparentPower.max.0}}</td>
              <td>{{apparentPower.min.0}}</td>
              <td>{{apparentPower.average.0}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 2"%}</td>
              <td>{{apparentPower.max.1}}</td>
              <td>{{apparentPower.min.1}}</td>
              <td>{{apparentPower.average.1}}</td>
          </tr>
          <tr>
              <td>{% trans "Phase 3"%}</td>
              <td>{{apparentPower.max.2}}</td>
              <td>{{apparentPower.min.2}}</td>
              <td>{{apparentPower.average.2}}</td>
          </tr>

      </table class ="table table-bordered">

    </div>
  </div>
</div>

{% endblock %}

src/report/templates/graphics/transductors_filter.html
{% extends "users/dashboard.html" %}
{% load i18n %}
{% block dashboard_content %}

<div class="margin">
  <h1 class="text-center">{% trans "List of Transductors:" %}</h>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">
        <table class ="table table-bordered">
          <tr>
            <th>{% trans "Serial Number" %}</th>
            <th>{% trans "IP Address" %}</th>
            <th>{% trans "Description" %}</th>
            <th>{% trans "Creation Date" %}</th>
            <th> </th>
          </tr>
          {% for transductor in transductors %}
          <tr>
            <td>{{transductor.serie_number}}</td>
            <td>{{transductor.ip_address}}</td>
            <td>{{transductor.description}}</td>
            <td>{{transductor.creation_date}}</td>
            <td><a href="{% url 'report:report' transductor.id %}"><button class ="btn btn-success" type="button" name="button"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span></button></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>

    </div>
  </div>


{% endblock %}